[tool.poetry]
name = "geojson_profil"
version = "0.1.0"
description = "Profilowanie danych GeoJSON"
authors = ["Twoje Imię <email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.45.1"
jsons = "^1.6.3"
ezdxf = "^1.4.2"
