[tool.poetry]
name = "profil-geojson-dxf"
version = "0.1.0"
description = "Streamlit app for generating DXF from GeoJSON"
authors = ["Twoje Imię <mail@domena.com>"]
package-mode = false  # ← KLUCZOWA LINIA

[tool.poetry.dependencies]
python
streamlit
jsons
ezdxf
pyproj
